[2024-01-20T16:17:23.508+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2023-10-13T00:00:00+00:00 [queued]>
[2024-01-20T16:17:23.516+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2023-10-13T00:00:00+00:00 [queued]>
[2024-01-20T16:17:23.519+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2024-01-20T16:17:23.536+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_s3_data> on 2023-10-13 00:00:00+00:00
[2024-01-20T16:17:23.542+0000] {standard_task_runner.py:57} INFO - Started process 1949 to run task
[2024-01-20T16:17:23.548+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_s3_data', 'read_s3_data', 'scheduled__2023-10-13T00:00:00+00:00', '--job-id', '2180', '--raw', '--subdir', 'DAGS_FOLDER/read.py', '--cfg-path', '/tmp/tmpx4_rzl_t']
[2024-01-20T16:17:23.550+0000] {standard_task_runner.py:85} INFO - Job 2180: Subtask read_s3_data
[2024-01-20T16:17:23.635+0000] {task_command.py:415} INFO - Running <TaskInstance: read_s3_data.read_s3_data scheduled__2023-10-13T00:00:00+00:00 [running]> on host dbb3489df186
[2024-01-20T16:17:23.725+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_s3_data' AIRFLOW_CTX_TASK_ID='read_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-13T00:00:00+00:00'
[2024-01-20T16:25:47.016+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2024-01-20T16:25:47.352+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
